### 原始请求

POST http://localhost:7001/
Content-Type: application/json

{
  "service": "com.maccoy.mcrpc.demo.api.IUserService",
  "methodSign": "selectUserById@1_java.lang.Integer",
  "args": [100]
}

### 重载方法请求

POST http://localhost:7001/
Content-Type: application/json

{
  "service": "com.maccoy.mcrpc.demo.api.IUserService",
  "methodSign": "findById@2_int",
  "args": [19]
}

### 原始请求

GET http://localhost:8001/find?timeout=500
#Content-Type: application/json
