server:
  port: 8001

mcrpc:
  providers: http://localhost:7001
  zkServer: localhost:2181
  zkRoot: mcrpc


app:
  id: app1
  namespace: public
  env: dev
  reties: 2
  timeout: 1000

logging:
  level:
    root: error
    com.maccoy.mcrpc: debug