server:
  port: 8001

mcrpc:
  zkServer: localhost:2181
  zkRoot: mcrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 1
    timeout: 1000
    faultLimit: 10
    halfOpenInitialDelay: 10_000
    halfOpenDelay: 60_000
    grayRatio: 0

app:
  id: SampleApp
apollo:
  cache-dir: /opt/apollo-2.2.0/data
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    namespaces: app,application

logging:
  level:
    root: error
    com.maccoy.mcrpc: debug