server:
  port: 7001

mcrpc:
  zkServer: localhost:2181
  zkRoot: mcrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 25
